# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Run a multi-line script
        run: |
          wget https://github.com/rr-debugger/rr/releases/download/5.4.0/rr-5.4.0-Linux-x86_64.tar.gz
          tar xvf rr-5.4.0-Linux-x86_64.tar.gz
          PATH="$PWD/rr-5.4.0-Linux-x86_64/bin:$PATH"
          export PATH
          LD_LIBRARY_PATH="$PWD/rr-5.4.0-Linux-x86_64/lib:$PWD/rr-5.4.0-Linux-x86_64/lib/rr:$LD_LIBRARY_PATH"
          which rr
          sudo sysctl -w kernel.perf_event_paranoid=1
          rr record true --args
          ls
